### ISSUE TITLE
Non-iterable NoneType object

### ISSUE THREAD

**Issue by emmess12** [congyingxia/ZeroShotCapsule#1]
Hello,
I'm getting the following error and I'm unable to understand it. Could you pls help me about it?
![Capture1](https://user-images.githubusercontent.com/49257894/58519442-f7275a00-81f6-11e9-914b-6d6bc8a7ca8a.PNG)

**Comment by congyingxia** [comment]
It might be the update_seen_routing function returns a NoneType Object. You can check if your seen_votes is empty.
