### ISSUE TITLE
Intent definition

### ISSUE THREAD

**Issue by Julietnj** [congyingxia/ZeroShotCapsule#2]
Hi, I wonder if the seen intents can be listed in unseen_intent array, I mean if I can test and predict some utterances of seen intents besides unseen ones. and is the number of intents limited? thanks very much.

**Comment by congyingxia** [comment]
Sure, you can also add seen intents in the unseen_intent array. There's a setting named Generalized zero-shot learning, which needs to predict all the seen and unseen classes together. The number of intents is not limited.

**Comment by abubakar-ucr** [comment]
@congyingxia, can you point me where this setting is in the code? Thanks

**Comment by congyingxia** [comment]
It's in the input_data.py. You can set the unseen_intent as you like.
